name: "Terraform GitHub Actions"
on:
  pull_request:
    types: [opened, synchronize, closed]
env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init
        working_directory:

      - name: Terraform Plan
        if: github.event.pull_request.state == 'open'
        run: terraform plan
        working_directory:

      - name: Terraform Apply
        if: github.event.pull_request.state == 'closed'
        run: terraform apply -auto-approve
        working_directory:
